name: matreshka
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter


  tele_web_app:
    git: https://github.com/yeikel16/tele_web_app.git
  
  flutter_window_close:
    git: https://github.com/zonble/flutter_window_close.git


  cupertino_icons: ^1.0.2
  crypto: ^3.0.3
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3
  firebase_core: ^2.25.5
  cloud_firestore: ^4.15.6
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.10+1
  easy_debounce: ^2.0.3
  percent_indicator: ^4.2.3
  sliver_tools: ^0.2.12
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Russia
      fonts:
        - asset: assets/fonts/Yarin-Regular.ttf

        
