// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsItkEM47Ytx8Xf5RTCPy_JVWyZplsznM',
    appId: '1:819751954263:web:d7bbe2e072d7fdf2374012',
    messagingSenderId: '819751954263',
    projectId: 'matreshki-13a87',
    authDomain: 'matreshki-13a87.firebaseapp.com',
    storageBucket: 'matreshki-13a87.appspot.com',
    measurementId: 'G-MR04Q2K5GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5KnN41qVDgzyQUfK9fCABJ8TRnUadZug',
    appId: '1:819751954263:android:e94b721b243ccafe374012',
    messagingSenderId: '819751954263',
    projectId: 'matreshki-13a87',
    storageBucket: 'matreshki-13a87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJs7r9a__x1wW4LX5vSKW_hJS6Wcbedgo',
    appId: '1:819751954263:ios:45f8eab83e15dca8374012',
    messagingSenderId: '819751954263',
    projectId: 'matreshki-13a87',
    storageBucket: 'matreshki-13a87.appspot.com',
    iosBundleId: 'com.example.matreshka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJs7r9a__x1wW4LX5vSKW_hJS6Wcbedgo',
    appId: '1:819751954263:ios:cfe7d70820832f13374012',
    messagingSenderId: '819751954263',
    projectId: 'matreshki-13a87',
    storageBucket: 'matreshki-13a87.appspot.com',
    iosBundleId: 'com.example.matreshka.RunnerTests',
  );
}
